#!/bin/sh
if [ "${LD_LIBRARY_PATH+set}" = "set" ] ; then
   export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/opt/virtualmoon/lib"
else
   export LD_LIBRARY_PATH="/opt/virtualmoon/lib"
fi
exec /opt/virtualmoon/bin/datlun "$@"
